### ISSUE TITLE
ERD Created

### ISSUE THREAD

**Issue by fmings** [nss-evening-cohort-26/pos-terminal-pizza-team#1]
# User Story
This user's experience will not be impacted by this ticket.

# Acceptance Criteria
ERD Table should be drawn.

# Dependencies
- Confirmation of datasets needed

# Dev Notes
- Confirmation of datasets needed

**Comment by alexberka** [comment]
[ERD Diagram](https://dbdiagram.io/d/HHPW-65ecb1d9b1f3d4062c860b4a)
