### ISSUE TITLE
Setup API Calls

### ISSUE THREAD

**Issue by fmings** [nss-evening-cohort-26/pos-terminal-pizza-team#30]
# User Story
The user's experience will not be directly impacted by this ticket.

# Acceptance Criteria
- When the navigates to any page referencing data
- the API functions will fetch the appropriate data

# Dependencies
- Initial File Setup should be complete
- Database will need to be setup
- Endpoints should be tested in Postman

# Dev Notes
- Endpoints should be tested in Postman

**Comment by alexberka** [comment]
Push #33
